/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd;

import backEnd.Canyon;
import backEnd.Enemy;
import backEnd.IA;
import backEnd.Laser;
import backEnd.Map;
import backEnd.Map1;
import backEnd.Map2;
import backEnd.Map3;
import backEnd.Plane;
import backEnd.Player;
import backEnd.Shop;
import backEnd.Tank;
import backEnd.machineGun;
import backEnd.mapCreatorView;
import backEnd.vehicle;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private Map map;
    private int mapNumber;
    private int vehicleNumber = 0;
    private int sizeMapX;
    private int sizeMapY;
    private Player newPlayer;
    private vehicle vehicleInBattle;
    private Shop shop = new Shop();
    private IA ia = new IA();
    private int noOfShifts = 1;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(Player newPlayer) {
        initComponents();
        this.newPlayer = newPlayer;

        this.setLocationRelativeTo(null);
        this.setTitle("Juego");
        this.getContentPane().setBackground(getBackground());
        LabelName.setText(newPlayer.getName());
        LabelOro.setText(String.valueOf(shop.getOro()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelOro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActionBox = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        DirectionBox = new javax.swing.JTextField();
        SpacesBox = new javax.swing.JTextField();
        BotonMoverse = new javax.swing.JButton();
        NoVehicle = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        PositionYAttack = new javax.swing.JTextField();
        PositionXAttack = new javax.swing.JTextField();
        BotonDisparar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        VehicleShop = new javax.swing.JMenuItem();
        WeaponShop = new javax.swing.JMenuItem();
        repairKits = new javax.swing.JMenuItem();
        restorativeObject = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del jugador");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Oro");

        LabelOro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ActionBox.setColumns(20);
        ActionBox.setRows(5);
        ActionBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(ActionBox);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Acciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(LabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelOro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelOro, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DirectionBox.setText("Direccion");

        SpacesBox.setText("Espacios");

        BotonMoverse.setBackground(new java.awt.Color(51, 51, 51));
        BotonMoverse.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Proyectos IPC vaqueras\\Proyecto1\\src\\main\\java\\Media\\Moverse.png")); // NOI18N
        BotonMoverse.setText("Moverse");
        BotonMoverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMoverseActionPerformed(evt);
            }
        });

        NoVehicle.setText("No. Vehiculo");

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Proyectos IPC vaqueras\\Proyecto1\\src\\main\\java\\Media\\CambiarVehiculo.png")); // NOI18N
        jButton2.setText("Elegir vehiculo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PositionYAttack.setText("Posicion en Y");

        PositionXAttack.setText("Posicion en X");

        BotonDisparar.setBackground(new java.awt.Color(51, 51, 51));
        BotonDisparar.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Proyectos IPC vaqueras\\Proyecto1\\src\\main\\java\\Media\\Disparar.png")); // NOI18N
        BotonDisparar.setText("Disparar");
        BotonDisparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDispararActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acciones");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpacesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(BotonMoverse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NoVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PositionYAttack, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(PositionXAttack))
                        .addGap(18, 18, 18)
                        .addComponent(BotonDisparar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BotonMoverse, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NoVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(DirectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SpacesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonDisparar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(PositionYAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PositionXAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Proyectos IPC vaqueras\\Proyecto1\\src\\main\\java\\Media\\Cargar.png")); // NOI18N
        jButton4.setText("Cargar Mapa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Proyectos IPC vaqueras\\Proyecto1\\src\\main\\java\\Media\\Rendirse.png")); // NOI18N
        jButton3.setText("Rendirse");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Opciones");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(0, 204, 204));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Jugar");

        jMenuItem1.setText("Cambiar Mapa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("Crear mapa aleatorio");
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Elegir dificultad");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 204, 204));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Tienda");

        VehicleShop.setText("Tienda de Vehiculos");
        VehicleShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleShopActionPerformed(evt);
            }
        });
        jMenu2.add(VehicleShop);

        WeaponShop.setText("Tienda de armas");
        WeaponShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeaponShopActionPerformed(evt);
            }
        });
        jMenu2.add(WeaponShop);

        repairKits.setText("Kits de reparacion");
        repairKits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairKitsActionPerformed(evt);
            }
        });
        jMenu2.add(repairKits);

        restorativeObject.setText("Objetos restauradores");
        restorativeObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restorativeObjectActionPerformed(evt);
            }
        });
        jMenu2.add(restorativeObject);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String[] optionMap = {"Mapa 1", "Mapa 2", "Mapa 3", "Mapa Aleatorio"};
        mapNumber = JOptionPane.showOptionDialog(this, "Que mapa quieres jugar", "Selector de mapa", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, optionMap, optionMap[0]);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BotonMoverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMoverseActionPerformed
        map.moveVehicle(parseInt(SpacesBox.getText()), DirectionBox.getText());
        mapCreatorView mapCreator = new mapCreatorView(jPanel1, map.getMap());
        mapCreator.createArray(sizeMapX, sizeMapY);
        ActionBox.append("Turno no. " + noOfShifts + ". Te haz movido\n");
        noOfShifts++;
        if (ia.isMode()) {
            enemyAttackEzMode();
        } else {
            enemyAttackHardMode();
        }

    }//GEN-LAST:event_BotonMoverseActionPerformed

    private void VehicleShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleShopActionPerformed
        String[] optionVehicle = {"1. Tanque", "2. Avion"};
        int vehicleNumber = JOptionPane.showOptionDialog(this, "Elige el vehiculo que quieres", "Selector de Vehiculos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, optionVehicle, optionVehicle[0]);
        if (vehicleNumber == 0) {
            newPlayer.addVehicle(new Tank());
            shop.buyTank();
            ActionBox.append("Turno no. " + noOfShifts + ". Compraste un Tanque\n");
        } else if (vehicleNumber == 1) {
            newPlayer.addVehicle(new Plane());
            shop.buyPlane();
            ActionBox.append("Turno no. " + noOfShifts + ". Compraste un Avion\n");
        }
        LabelOro.setText(String.valueOf(shop.getOro()));

    }//GEN-LAST:event_VehicleShopActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (parseInt(NoVehicle.getText()) == 1) {
            map.setVehicle(newPlayer.getVehicle(0));
        } else if (parseInt(NoVehicle.getText()) == 2) {
            map.setVehicle(newPlayer.getVehicle(1));
        } else {
            map.setVehicle(newPlayer.getVehicle(2));
        }
        ActionBox.append("Turno no." + noOfShifts + ". Cambiaste de vehiculo\n");
        noOfShifts++;

        if (ia.isMode()) {
            enemyAttackEzMode();
        } else {
            enemyAttackHardMode();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (mapNumber == 0) {
            Map1 map1 = new Map1(newPlayer.getVehicle(vehicleNumber));
            map = new Map(map1.getMap1(), 2, 5, 6, 6, newPlayer.getVehicle(vehicleNumber), new Enemy(1, 0), new Enemy(2, 0), new Enemy(4, 1));
            mapCreatorView mapCreator = new mapCreatorView(jPanel1, map.getMap());
            mapCreator.createArray(6, 6);
            sizeMapX = 6;
            sizeMapY = 6;

        } else if (mapNumber == 1) {
            Map2 map2 = new Map2(newPlayer.getVehicle(vehicleNumber));
            map = new Map(map2.getMap2(), 2, 5, 10, 10, newPlayer.getVehicle(vehicleNumber), new Enemy(4, 0), new Enemy(5, 1), new Enemy(6, 7));
            mapCreatorView mapCreator = new mapCreatorView(jPanel1, map.getMap());
            mapCreator.createArray(10, 10);
            sizeMapX = 10;
            sizeMapY = 10;

        } else {
            Map3 map3 = new Map3(newPlayer.getVehicle(vehicleNumber));
            map = new Map(map3.getMap3(), 7, 13, 15, 15, newPlayer.getVehicle(vehicleNumber), new Enemy(3, 3), new Enemy(3, 11), new Enemy(6, 7));
            mapCreatorView mapCreator = new mapCreatorView(jPanel1, map.getMap());
            mapCreator.createArray(15, 15);
            sizeMapX = 15;
            sizeMapY = 15;

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void WeaponShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeaponShopActionPerformed
        String[] weaponOptions = {"1. Cañon", "2. Ametralladora", "3. Laser"};
        int weaponNumber = JOptionPane.showOptionDialog(this, "Elige el arma que quieres", "Selector de Armas", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, weaponOptions, weaponOptions[0]);
        shop.buyWeapon(weaponNumber);
        if (shop.canBuy()) {
            if (weaponNumber == 0) {
                newPlayer.getVehicle(vehicleNumber).addWeapon(new Canyon());
                ActionBox.append("Compraste un cañon\n");
            } else if (weaponNumber == 1) {
                newPlayer.getVehicle(vehicleNumber).addWeapon(new machineGun());
                ActionBox.append("Compraste una ametralladora\n");
            } else {
                newPlayer.getVehicle(vehicleNumber).addWeapon(new Laser());
                ActionBox.append("Compraste un Laser\n");
            }
        }
        LabelOro.setText(String.valueOf(shop.getOro()));
    }//GEN-LAST:event_WeaponShopActionPerformed

    private void repairKitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairKitsActionPerformed
        String[] kitOption = {"1. Kit de reparacon menor", "2. Kit de reparacion mayor"};
        int kitNumber = JOptionPane.showOptionDialog(this, "Elige el arma que quieres", "Selector de Armas", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, kitOption, kitOption[0]);
        shop.buyKits(kitNumber);
        if (kitNumber == 0) {
            newPlayer.getVehicle(vehicleNumber).repair(25);
            ActionBox.append("Turno no. " + noOfShifts + ". Compraste un kit de reparacion base\n");
        } else {
            newPlayer.getVehicle(vehicleNumber).repair(50);
            ActionBox.append("Turno no. " + noOfShifts + ". Compraste un kit de reparacion avanzado\n");
        }
        LabelOro.setText(String.valueOf(shop.getOro()));
        noOfShifts++;
    }//GEN-LAST:event_repairKitsActionPerformed

    private void restorativeObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restorativeObjectActionPerformed
        String[] kitOption = {"Comprar objeto restaurador "};
        int kitNumber = JOptionPane.showOptionDialog(this, "Elige el arma que quieres", "Selector de Armas", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, kitOption, kitOption[0]);
        shop.buyRepair();
        if (kitNumber == 0) {
            newPlayer.getVehicle(vehicleNumber).restore();
            ActionBox.append("Compraste un objeto restaurador\n");
        }
        LabelOro.setText(String.valueOf(shop.getOro()));

    }//GEN-LAST:event_restorativeObjectActionPerformed

    private void BotonDispararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDispararActionPerformed
        map.attack(parseInt(PositionYAttack.getText()) - 1, parseInt(PositionXAttack.getText()) - 1);
        mapCreatorView mapCreator = new mapCreatorView(jPanel1, map.getMap());
        mapCreator.createArray(sizeMapX, sizeMapY);
        ActionBox.append("Turno no. " + noOfShifts + ". Haz intentado atacar\n");
        noOfShifts++;

        if (ia.isMode()) {
            enemyAttackEzMode();
        } else {
            enemyAttackHardMode();
        }
    }//GEN-LAST:event_BotonDispararActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String[] modeOptions = {"1. Facil ", "2. Dificl"};
        int dificult = JOptionPane.showOptionDialog(this, "Elige la dificultad", "Selector de dificultad", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, modeOptions, modeOptions[0]);
        if (dificult == 0) {
            ia.setMode(true);
        } else {
            ia.setMode(false);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void enemyAttackEzMode() {
        Enemy[] enemies = map.getEnemiesPosition();
        for (int i = 0; i <= 2; i++) {

            if (map.getEnemy(i) != null) {
                if (ia.shootingDirection()) {
                    Enemy enemy = enemies[i];
                    int posicionX = enemies[i].attackInX(sizeMapX);
                    int posicionY = enemies[i].getPositionY();
                    ActionBox.append("Enemigo ataco en la casilla: " + posicionY + ", " + posicionX + "\n");
                    map.enemyAttack(enemies[i].getPositionY(), posicionX);
                } else {
                    Enemy enemy = enemies[i];
                    int posicionY = enemies[i].attackInY(sizeMapY);
                    int posicionX = enemies[i].getPositionX();
                    ActionBox.append("Enemigo ataco en la casilla: " + posicionY + ", " + posicionX + "\n");
                    map.enemyAttack(posicionY, enemies[i].getPositionX());
                }
            } else {
                ActionBox.append(" no hay enemigo perro\n");
            }
        }
    }

    public void enemyAttackHardMode() {
        Enemy[] enemies = map.getEnemiesPosition();
        for (int i = 0; i <= 2; i++) {
            if (ia.shooting(map.getPlayerPosition().getPositionY(), map.getPlayerPosition().getPositionX(), enemies[i].getPositionY(), enemies[i].getPositionX())) {
                map.getNewVehicle().attacked(25);
                ActionBox.append("Ten ha disparado");
            }
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ActionBox;
    private javax.swing.JButton BotonDisparar;
    private javax.swing.JButton BotonMoverse;
    private javax.swing.JTextField DirectionBox;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelOro;
    private javax.swing.JTextField NoVehicle;
    private javax.swing.JTextField PositionXAttack;
    private javax.swing.JTextField PositionYAttack;
    private javax.swing.JTextField SpacesBox;
    private javax.swing.JMenuItem VehicleShop;
    private javax.swing.JMenuItem WeaponShop;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem repairKits;
    private javax.swing.JMenuItem restorativeObject;
    // End of variables declaration//GEN-END:variables
}
